### ISSUE TITLE
python: add example python script for python client

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/docs#27]
Add a more comprehensive python example in /docs/client/python.md

PR for this issue:
https://github.com/OpenLineage/docs/pull/30

**Comment by merobi-hub** [comment]
@howardyoo noticed that you added some examples to the site. Would you still like to see an example added to this file? Thanks

**Comment by howardyoo** [comment]
Yes, @merobi-hub , the example.md contains examples on the openlinage json data format - I think we may need an example of fully working python script right at the bottom of the page. I am currently working on one for python.

**Comment by merobi-hub** [comment]
@howardyoo when I was writing my blog post on the Python client, Maciej referred me to this as a reference: https://github.com/OpenLineage/OpenLineage/blob/main/integration/dbt/scripts/dbt-ol. Maybe it could serve as an example or a resource to create one...

**Comment by howardyoo** [comment]
Hmm. maybe it might make more sense if we had `/examples` directory and have individual examples on various integration/cases, as opposed to just a single `example.md`. Feel free to work on it to refactor it.
