### ISSUE TITLE
airflow: Unclear that Marquez must be running independently 

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/docs#6]
https://openlineage.io/integration/apache-airflow/

The docs supporting the Airflow integration do not currently make clear that Marquez must be started separately/independently of Airflow.

**Comment by rossturk** [comment]
@merobi-hub is this still relevant with the new doc site?

**Comment by merobi-hub** [comment]
I think it's fixed now. The docs link to marquez/examples/airflow, where the quick start guide now includes a command that starts up Marquez and Airflow at the same time and makes this clear.
