### ISSUE TITLE
[integration/airflow, doc] document the new DefaultExtractor and its usage

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/docs#68]
The recent OpenLineage for airflow integration has what's called DefaultExtractor which can act as the 'base' extractor for all of Airflow's operator extractors - and thus users would not have to create as many extractors as they have to. However, there is no 'documentation' about it, so we need to add the doc to explain what's changed, and how it's going to impact users.

**Comment by JDarDagran** [comment]
Hey @howardyoo, we do have DefaultExtractor documented [here](https://openlineage.io/docs/integrations/airflow/operator). Would you want to have it somehow more exposed?

**Comment by howardyoo** [comment]
Hi @JDarDagran , yes. The Default Extractor documented above is not very conspicuous.
Perhaps maybe we could add a section to the menu:
![image](https://user-images.githubusercontent.com/32691630/207361706-113050f9-fcff-42ee-aa06-c198e5d63463.png)
Under apache airflow that has 'DefaultExtractor' as the first item, and explain how the default extractor works.

**Comment by howardyoo** [comment]
Thanks!
