### ISSUE TITLE
[DOCS] Broken Link in SQL Parser Doc

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/docs#81]
There is a broken link to the SQL parser tester, which now seems to be a bunch of different testers based on dialect. Not sure how this would be best fixed.
Doc:
https://github.com/OpenLineage/docs/blob/main/docs/development/sql.md

**Comment by mobuchowski** [comment]
Will rework this doc after merging this:

https://github.com/OpenLineage/OpenLineage/compare/main...feature/column-level-lineage

**Comment by merobi-hub** [comment]
This link is still broken. Does the page need a re-do at this point? @mobuchowski

**Comment by mobuchowski** [comment]
Probably best to remove that page for now, it's not relevant anymore.
