### ISSUE TITLE
[Guides] additional guides needed

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/docs#93]
### Integrations

We currently have coverage for Spark, Airflow and dbt.

Needed: 
- Dagster (?)
- Flink
- SQL
- Common
    - Great Expectations
    - BigQuery
    - Redshift 

### How-tos

We currently have a how-to on backfilling DAGs with Marquez

Needed:
- Writing custom facets
- Writing new extractors?

Am I missing anything?

**Comment by Sheeri** [comment]
We need a guide on 'how to translate your lineage to openLineage format'.
